version: "3.9"
services:
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - app
  app:
    container_name: app_2
    restart: always
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    container_name: mongo_2
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
